[platformio]
default_envs = esp32bbc

[env:esp32bbc]
platform = espressif32@6.4.0
board = esp32dev
framework = espidf

board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DFABGL_HAS_PS2KEYBOARD=1
    -DFABGL_HAS_PS2MOUSE=0
    -DFABGL_HAS_I2S=1
    -O3
    -ffunction-sections
    -fdata-sections
    -mlongcalls

board_upload.flash_size = 4MB

lib_deps = fdivitto/FabGL@^1.0.9
